
module.exports.zeroDevices = {
  device: []
};


module.exports.twoDevices = {
  device: [
    {
      id: '1268445',
      clientDeviceId: '12',
      name: 'Allmänbelysning',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0,
      devices: '1283624,1283628'
    },
    {
      id: '1283624',
      clientDeviceId: '23',
      name: 'Allmänbelysning Plan 1',
      state: 1,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1,
      devices: '1193618,1193622'
    }
  ]
};

module.exports.duplicateDevices = {
  device: [
    {
      id: '1268445',
      clientDeviceId: '12',
      name: 'Allmänbelysning',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0,
      devices: '1283624,1283628'
    },
    {
      id: '1268445',
      clientDeviceId: '12',
      name: 'Allmänbelysning',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0,
      devices: '1283624,1283628'
    }
  ]
};

/*
var sample = {
  device: [
    {
      id: '1268445',
      clientDeviceId: '12',
      name: 'Allmänbelysning',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0,
      devices: '1283624,1283628'
    },
    {
      id: '1283624',
      clientDeviceId: '23',
      name: 'Allmänbelysning Plan 1',
      state: 1,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1,
      devices: '1193618,1193622'
    },
    {
      id: '1283628',
      clientDeviceId: '24',
      name: 'Allmänbelysning Plan 2',
      state: 1,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1,
      devices: '1196562,1196553'
    },
    {
      id: '1269214',
      clientDeviceId: '13',
      name: 'Balkongbelysning',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1275046',
      clientDeviceId: '18',
      name: 'Brytare Sänglampa Höger',
      state: 1,
      statevalue: null,
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1274971',
      clientDeviceId: '17',
      name: 'Brytare Sänglampa Vänster',
      state: 1,
      statevalue: null,
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1268183',
      clientDeviceId: '11',
      name: 'Garagebänk',
      state: 2,
      statevalue: '0',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1268168',
      clientDeviceId: '10',
      name: 'Garagebänksbrytare - Höger',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1268166',
      clientDeviceId: '9',
      name: 'Garagebänksbrytare - Vänster',
      state: 1,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1282591',
      clientDeviceId: '22',
      name: 'Laddare - Garage - Underhållsladdning',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1274897',
      clientDeviceId: '14',
      name: 'Laddare Garage',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1196562',
      clientDeviceId: '6',
      name: 'Lampor - Allrum',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1193618',
      clientDeviceId: '1',
      name: 'Lampor - Kontor',
      state: 1,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1294232',
      clientDeviceId: '27',
      name: 'Lampor - Kontor - Nexa',
      state: 1,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1196553',
      clientDeviceId: '5',
      name: 'Lampor - Sovrum och Gästrum',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1193622',
      clientDeviceId: '2',
      name: 'Lampor - Vardagsrum',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 1
    },
    {
      id: '1285066',
      clientDeviceId: '25',
      name: 'Larm - Larmat',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1285067',
      clientDeviceId: '26',
      name: 'Larm - Skalskyddat',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1274935',
      clientDeviceId: '15',
      name: 'Sänglampa - höger',
      state: 2,
      statevalue: '52',
      methods: 19,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1274948',
      clientDeviceId: '16',
      name: 'Sänglampa - vänster',
      state: 1,
      statevalue: '69',
      methods: 19,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1281811',
      clientDeviceId: '19',
      name: 'Strålkastare - Köksaltan',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1281982',
      clientDeviceId: '20',
      name: 'Strålkastare - Matplats',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1267076',
      clientDeviceId: '8',
      name: 'Strålkastare - Parkering',
      state: 2,
      statevalue: 'unde',
      methods: 3,
      type: 'device',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0
    },
    {
      id: '1282078',
      clientDeviceId: '21',
      name: 'Trädgårdsbelysning',
      state: 2,
      statevalue: null,
      methods: 3,
      type: 'group',
      client: '200262',
      clientName: 'Gudö Ekväg 24',
      online: '1',
      editable: 1,
      ignored: 0,
      devices: '1281811,1281982'
    }]
};
*/
